[project]
name = "humidity-simulator"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Your Name", email = "example@example.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.1",
    "pandas>=2.0.0",
    "pydantic>=2.0.0",
    "uvicorn[standard]>=0.34.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/humidity_simulator"]

[tool.hatch.version]
path = "src/humidity_simulator/__init__.py"

[dependency-groups]
dev = [
    "coverage>=7.7.0",
    "deptry>=0.23.0",
    "httpx>=0.28.0",
    "mypy>=1.15.0",
    "poethepoet>=0.33.1",
    "pytest>=8.3.5",
    "ruff>=0.11.0",
]

[tool.ruff]
target-version = "py312"
show-fixes = true
extend-exclude = [".venv"]
line-length = 120
lint.select = [
    "A",
    "ANN",
    "ARG",
    "B",
    "BLE",
    "C4",
    "C90",
    "E",
    "ERA",
    "F",
    "FBT",
    "FURB",
    "I",
    "INP",
    "ISC",
    "N",
    "PERF",
    "PTH",
    "RET",
    "RUF",
    "S",
    "SIM",
    "SLF",
    "T20",
    "UP",
    "W",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101", "SLF001", "FBT001"]

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.mypy]
python_version = "3.12"
ignore_missing_imports = true
disallow_untyped_defs = true
exclude = ".venv|__ignore__"

[tool.coverage.run]
branch = true
source = ["src"]
omit = ["tests/*"]

[tool.coverage.report]
skip_empty = true

[tool.deptry]
known_first_party = ["humidity_simulator"]
per_rule_ignores = {DEP002 = ["uvicorn"]}

[tool.poe.tasks]

[tool.poe.tasks.fmt]
help = "Format the project"
sequence = ["fmt-ruff-format", "fmt-ruff-check"]

[tool.poe.tasks.lint]
help = "Lint the project"
sequence = ["lint-ruff-format", "lint-ruff-check", "lint-mypy", "lint-deps"]

[tool.poe.tasks.test]
help = "Test the project"
sequence = ["test-run", "test-report", "docker-compose-down"]

[tool.poe.tasks.coverage]
help = "View the test coverage report"
sequence = ["cov-html", "cov-view"]

[tool.poe.tasks.all]
help = "Run all pre-commit checks"
sequence = ["fmt", "lint", "test"]

[tool.poe.tasks.fmt-ruff-check]
cmd = "ruff check --fix-only src tests"

[tool.poe.tasks.fmt-ruff-format]
cmd = "ruff format src tests"

[tool.poe.tasks.lint-ruff-check]
cmd = "ruff check src tests"

[tool.poe.tasks.lint-ruff-format]
cmd = "ruff format --check src tests"

[tool.poe.tasks.lint-mypy]
cmd = "mypy src tests"

[tool.poe.tasks.lint-deps]
cmd = "deptry src"

[tool.poe.tasks.test-run]
cmd = "coverage run -m pytest tests/"
deps = ["docker-compose-up"]

[tool.poe.tasks.test-report]
cmd = "coverage report -i"

[tool.poe.tasks.cov-html]
cmd = "coverage html"

[tool.poe.tasks.cov-view]
cmd = "python -m webbrowser -t $POE_ROOT/htmlcov/index.html"

[tool.poe.tasks.docker-compose-up]
help = "Build and start the Docker container"
sequence = ["_docker-compose-start", "_docker-wait"]

[tool.poe.tasks._docker-compose-start]
cmd = "docker compose up -d --build"

[tool.poe.tasks._docker-wait]
cmd = "python tests/utils/wait_for_server.py"

[tool.poe.tasks.docker-compose-down]
help = "Stop and remove the Docker container"
cmd = "docker compose down"
